### ISSUE TITLE
If we turn on the "hide comment section", the option to "add cover" dissapear.  

### ISSUE THREAD

**Issue by AlexRaven-Arch** [joansnotion/NotionMate#1]
If we turn on the "hide comment section", the option to "add cover" dissapear.  Example in the video.

  

https://github.com/joansnotion/NotionMate/assets/104816241/fa510525-23a4-431e-b0a5-2bf4feccf5c6

**Comment by joansnotion** [comment]
Thank you for your feedback. 
Fixed, updated to Notion Mate v1.4.3.
