### ISSUE TITLE
Mark Manager / Colored Text is not working

### ISSUE THREAD

**Issue by crekri** [joansnotion/NotionMate#11]
Will be buying the plugin if it's fixed. (It's the main reason I want to use the plugin in the first place)

**Comment by joansnotion** [comment]
Okay, I'll fix it as soon as I can.

**Comment by joansnotion** [comment]
Can you provide a screenshot or video? Because I have tested it and I don't find any problem.

**Comment by crekri** [comment]
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/7e2831fe-207a-4c3a-be8c-5d6bfda6ba5a"> It seems like colored block are not supported. Is it possible to support it as well? (Perhaps make this customizable in settings)

**Comment by joansnotion** [comment]
Can you make it public to me and I'll copy it to my workspace.

**Comment by joansnotion** [comment]
I already know the problem, but this causes duplicate entries to appear.

**Comment by crekri** [comment]
How about making it a checkbox? Instead of having the user choose "Colored Texts" or "Comments", the user can choose to enable either "Colored Texts" /  "Colored Blocks" / "Comments" (Can enable all three at once, or only one of them?)

I actually wouldn't mind if there's duplicates, since I will be responsible for checking both Colored Texts and Colored blocks. (Although ideally I would like to have some content check in place to skip duplicate entries)

**Comment by joansnotion** [comment]
It will take me a bit of time, I think there are some that are necessary to support, I'll let you know when I've finished it, thanks for the suggestion.

**Comment by joansnotion** [comment]
![image](https://github.com/user-attachments/assets/5e080400-ce2d-4e67-995d-ad7b5fc226ab)

Please update to Notion Mate `V2.1.7` and set the Search Mode of Mark Manager to `Text&Block`.

![image](https://github.com/user-attachments/assets/be383226-6600-4c50-aece-7601ae910bab)

**Comment by crekri** [comment]
The new Mark manager is working! Will be buying the extension, thank you!
