### ISSUE TITLE
Hide Sidebar Toolbuttons is not working

### ISSUE THREAD

**Issue by lwfeather** [joansnotion/NotionMate#12]
Hi, i'm using Chrome ( version:130.0.6723.92 ), and i found out that the "Hide Sidebar Toolbuttons" is not working even after refreshing the page.
Hope u can fix this, thanks for your help!

**Comment by joansnotion** [comment]
The issue has been fixed pending chrome store review.
Please update the version to v2.1.8.

**Comment by lwfeather** [comment]
OK, i'll try it when v2.1.8 release, thanks a lot!
