### ISSUE TITLE
Outline is out of position

### ISSUE THREAD

**Issue by lwfeather** [joansnotion/NotionMate#14]
Hi Joans
im using Chrome ver.131.0.6778.140
as title, the outline is out of position, like the pic below
![image](https://github.com/user-attachments/assets/b31516da-436d-4f8e-b19e-946e35cf69af)
Hope u can fix it, many thanks!

**Comment by joansnotion** [comment]
It will be fixed today, please wait for chrome store review, thank you for your support.
