### ISSUE TITLE
outline bugs

### ISSUE THREAD

**Issue by tenfroelich** [joansnotion/NotionMate#2]
outline does not work properly in long files, it does not show the current header, it stops in random positions.

**Comment by joansnotion** [comment]
Thank you for your issues. Can you provide demo? After my tests, I can't find any problems so far.

**Comment by tenfroelich** [comment]
https://github.com/joansnotion/NotionMate/assets/97684350/bcf02299-63b8-435f-b6c0-c59f52b4d2ac

**Comment by joansnotion** [comment]
Thanks for your reply and for the demo you provided. The Layout of the outline is Sticky mode. I don't have such a big document for you, could you please share it with me? If possible, this will help me fix as soon as possible, thank you, you can set the notion document to publish and send me the share link, thank you!

**Comment by tenfroelich** [comment]
https://glen-handsaw-b4c.notion.site/13-Guacamole-Lite-b28ed010d13248c6984c6d8a0d497dfe?pvs=4

I will exclude this comments after the bug is solved as this documents are personal

**Comment by joansnotion** [comment]
I will repair it as soon as possible after testing, thank you!

**Comment by joansnotion** [comment]
notion mate has been updated to v1.5.5, and the issue has been fixed, along with the dark theme color inconsistency in the lower right corner, and the emoji does not display.

**Comment by joansnotion** [comment]
https://github.com/joansnotion/NotionMate/assets/155308134/e6f841d7-4095-4c6e-b41c-8c503f56fa63

**Comment by tenfroelich** [comment]
That's amazing! thank you so much, it's perfect now. I ask you to remove this last video since i dont want to share those informations.

**Comment by joansnotion** [comment]
Very sorry, I will delete it.

**Comment by tenfroelich** [comment]
No problem at all, I'm glad it worked!
