### ISSUE TITLE
outline issue

### ISSUE THREAD

**Issue by lwfeather** [joansnotion/NotionMate#3]
Hi, im using Chrome, version:123.0.6312.86.
The problem is, when i turn on the outline feature(embed mode), the outline will overlap with my content, and it doesn't work out.
BTW, this problem just happened after the official error two days ago.
Hope u help fixing this, thx a lot!

**Comment by joansnotion** [comment]
Can you take a screenshot of the question?

**Comment by joansnotion** [comment]
The problem has been resolved, all features have been tested, thank you for your feedback!

**Comment by lwfeather** [comment]
Sure, as the file below.
![Outline overlap](https://github.com/joansnotion/NotionMate/assets/158407931/5d20e173-e1be-4554-bb93-e6c145b61936)

**Comment by joansnotion** [comment]
I have uploaded to chrome Store, the latest version is v1.6.7, please wait for approval!

**Comment by lwfeather** [comment]
OK, thx for working on it so efficiently!
