### ISSUE TITLE
Timeline bug

### ISSUE THREAD

**Issue by Wlj2002** [joansnotion/NotionMate#5]
当插件启动时，Timeline下的三个选项消失了（放了一张未开启插件的图做对比），并且方块无法支持拖动更改时间（当插件关闭时可以）
您的插件做的非常便捷美观，感谢打造如此优秀的插件。辛苦您的付出！
<img width="385" alt="image" src="https://github.com/joansnotion/NotionMate/assets/99466655/73b15470-b6c8-4fc9-ab99-9b398287419a">

<img width="354" alt="image" src="https://github.com/joansnotion/NotionMate/assets/99466655/bb0dd80c-c2bf-4830-a1b2-f8948fa3f6d5">

https://github.com/joansnotion/NotionMate/assets/99466655/dd5250fc-59b9-41e0-b265-9d78bfb8f4a7

**Comment by joansnotion** [comment]
I haven't found any such issues yet, so I suggest you close the other extensions for now and try again

**Comment by Wlj2002** [comment]
I'm not sure if it's my computer problem, but I rebooted and tried it once. Disabled other plugins as well. but it doesn't help.
 You can check out this video.

https://github.com/joansnotion/NotionMate/assets/99466655/dd9179a5-f2ad-4dde-8aaa-e1be81faa542

**Comment by joansnotion** [comment]
Thank you for your demo. I have found the problem and will fix it today.

**Comment by Wlj2002** [comment]
Thank you very much.

**Comment by joansnotion** [comment]
Waiting for chrome Store approval, the latest version is v1.7.7.

**Comment by joansnotion** [comment]
If the problem is solved, please close the issue.

**Comment by Wlj2002** [comment]
No problem
