### ISSUE TITLE
When articles are very long and have a large number of headings, typing jams occur

### ISSUE THREAD

**Issue by Wlj2002** [joansnotion/NotionMate#6]
When articles are very long and have a large number of headings, typing jams occur. But if you turn off the outline function, it goes back to normal. I tried this on two different computers, one mac, one Windows , both had it. The phenomenon is evident in my 6,000-word article with a complex headline structure. You can use my article to duplicate it to your own workspace to get a feel for it. 

https://best-jump-faf.notion.site/Java-ff643d2780a74323a69e58d8bbd7f7c6?pvs=4

**Comment by joansnotion** [comment]
I tried, but I did not reproduce, can you give me a demo video?

**Comment by Wlj2002** [comment]
No problem, You can focus on the deletion of the character.

https://github.com/joansnotion/NotionMate/assets/99466655/58267413-6642-49c4-80d7-1e228515b7c0

**Comment by joansnotion** [comment]
Close the other plugins and try again, I copied your article, but it works fine.

**Comment by Wlj2002** [comment]
OK

**Comment by joansnotion** [comment]
Does the problem still exist?

**Comment by Wlj2002** [comment]
Yeah, I'm gonna try it again tomorrow on my friend's computer.

**Comment by Wlj2002** [comment]
Thank you very much. That's very kind of you! Have a nice day.
