### ISSUE TITLE
change custom font issue

### ISSUE THREAD

**Issue by tenfroelich** [joansnotion/NotionMate#7]
I have set the font cascadia code which is a monospace font, but the real is different as you can see in the image below.
![Untitled](https://github.com/joansnotion/NotionMate/assets/97684350/d41ac9f4-7770-4740-93d9-8e3568d15b21)

**Comment by joansnotion** [comment]
I will test it. If there is any problem, it will be repaired today. Thank you for your issue.

**Comment by joansnotion** [comment]
In my tests, it works very well, which language do you use? Does the font support this language?

**Comment by tenfroelich** [comment]
It is working properly in code blocks, it is not working in menus and main texts.

**Comment by tenfroelich** [comment]
neither in outline. By the way, I am really impressed with the last updates, you're building the best notion extension! The only thing that is working better in notion-enhancer is the font chooser. I would like to suggest the extension notion syntax highlight er, it changes the pattern of colors of code block which are pretty bad in notion, without overwriting the highlight that we do like notion enhancer.

**Comment by tenfroelich** [comment]
that would be a great improvement

**Comment by joansnotion** [comment]
Thanks for the suggestion, because notion mate's font selector works fine on my computer, and I've tested it on other computers and it still works fine.
You can try to test it after closing other chrome extensions.

**Comment by joansnotion** [comment]
The notion syntax highlighting feature is already in my next plan and will need to wait a little longer because it needs to match themes.

**Comment by tenfroelich** [comment]
That's Great!  Even without other extensions, it is still applying a serif type font instead of cascadia code or jetbrains.  
That a print screen from your extension

![nt-mate](https://github.com/joansnotion/NotionMate/assets/97684350/48e5623f-7429-44bd-8ecb-df54d660c363)
And this is from notion enhancer:
![nt-enh](https://github.com/joansnotion/NotionMate/assets/97684350/713621b0-0394-4495-800f-5dadce8e82bd)

**Comment by joansnotion** [comment]
Is your operating system windows or linux?

**Comment by joansnotion** [comment]
I seem to have found the reason, please keep an eye on notion mate v1.8.4 and contact me if you still have problems! Thank you!

**Comment by joansnotion** [comment]
Have you tried the [Notion Syntax Highlighter](https://chrome.google.com/webstore/devconsole/85865904-e2a1-45ae-a89e-b85a267ccd6b/pplckfedebdimphneohkmhlmhompgpmn) extension?

I plan to implement such a feature that you can do all in notion with just notion mate.

**Comment by tenfroelich** [comment]
I worked just fine! Thank you ! I am already using [Notion Syntax Highlighter](https://chrome.google.com/webstore/devconsole/85865904-e2a1-45ae-a89e-b85a267ccd6b/pplckfedebdimphneohkmhlmhompgpmn) and I am looking forward to see this feature in notion mate!
