### ISSUE TITLE
强烈建议增加一个开关：页面所有图片自动居中对齐

### ISSUE THREAD

**Issue by imazzystar** [joansnotion/NotionMate#8]
因为使用一些Notion Clipper时，例如Save to Notion，在Notion中剪切的页面，图片总是会自动左对齐，在一些内容较长，图片居多的页面，手动逐张去居中对齐实在令人蛋疼。
同理，还可以增加所有图片全部自动左、右对齐开关:)
谢谢开发者！扩展非常美妙！

**Comment by joansnotion** [comment]
Thanks for your suggestion, I will consider implementing it in the next version.

**Comment by imazzystar** [comment]
thank you!

**Comment by joansnotion** [comment]
I've released Notion Mate v2.0.0 with the added autoalign image feature. 
Please wait for chrome store review, thank you for your suggestion, if the new feature can solve your problem, please close this issue, thank you!

![align_image](https://github.com/joansnotion/NotionMate/assets/155308134/75fbc9d6-caf9-435f-932f-4a6682d4fb6b)
